### ISSUE TITLE
Make it possible to change theme on arrow keypresses

### ISSUE THREAD

**Issue by tibuurcio** [dawnlabs/carbon#154]
Hi guys, thank you all for this awesome project! 👌🏼👏🏼 
_I've not used the issue template since this is a feature request_

First thing I tried to do on the web page was to change the theme on arrow keys to see how they look, similar to how VSCode does it. I noticed it wasn't possible and then tried to implement it. I have a somewhat working solution by now!

![carbon](https://user-images.githubusercontent.com/5959178/34923157-f6a83c38-f977-11e7-8ad4-77c487c1425c.gif)

I would like to know if you guys think it's a good idea so that I can than create a PR to work better on it! 

I have yet to figure out how to make the dropdown also scroll (maybe keep a ref to it and use [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) ? 🤔). Also, I'm not very familiar with Next.js... Is it ok to add and eventHandler to the window object directly?

Thank you all again! Haven't had the opportunity to use it but will definitely do it.

**Comment by jakedex** [comment]
This is a great idea, @tibuurcio! I think it'd be great to have for both the theme and language dropdowns. 

As for making the dropdown scroll, you might want to look into [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView). Since we're using react, you'll just want to listen for the `keydown` event inside of the dropdown component (something like [this](https://stackoverflow.com/questions/42036865/react-how-to-navigate-through-list-by-arrow-keys)).

**Comment by mfix22** [comment]
Hey guys,
I think we should use [`downshift`](https://github.com/paypal/downshift) to handle this. It handles key(down|up) out of the box and makes it super easy to implement [type-ahead](https://codesandbox.io/s/82m2px40q9) (something we might want to do for this in the future as well).

**Comment by tibuurcio** [comment]
@jakedex Thanks for the suggestion about scrollIntoView, will take a look into it!

@mfix22 Downshift is such a great idea for this! I've never used it but I'm familiar with the render props concept behind it. Great opportunity to learn, will try to hack something with it when I have some time.
