### ISSUE TITLE
Add optional watermark to generated image

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/carbon#178]
As many have pointed out, adding a watermark to the exported image would help mitigate people repeatedly asking about how the screenshot was generated, etc. 

(cc @kitze :smirk:)

**Comment by yeskunall** [comment]
This is a 👎 as a feature for me because 1. if it's optional, I won't ever want to add that watermark and 2. part of Carbon's beauty is that it does not impose itself as a service onto the user. Take for example the _free_ version of [Bandicam](https://www.bandicam.com/), that always adds a certain watermark when using it.

However, if it _is_ requested by a vast multitude of people, adding it as an optional feature may not be *__that__* bad of an idea 😅

**Comment by mfix22** [comment]
1. No matter what, we would keep the watermark/image to the bottom right of the image to it avoids covering as much text as possible.
2. What would you think about it if you could add your own custom watermark to the editor, allowing you to make custom "branded" Carbon screenshots.
3. Thanks for voicing your though, @yeskunall. Just want to put it out there, that we don't want to impose the Carbon brand on the screenshots (in fact @jakedex has been against the watermark all along), and only raised this issue since people request it a lot on twitter. We want to collect more opinions before implementing this.

**Comment by yeskunall** [comment]
Perfectly cool with me, you guys. 😅 sorry, it might have seemed like I was forcing my opinion, but let's see how this conversation goes! 😁
