### ISSUE TITLE
color syntax and image bug in JavaScript

### ISSUE THREAD

**Issue by konojunya** [dawnlabs/carbon#328]
**bug in color sytax**

Sometimes JavaScript syntax does not apply. As I encountered myself, the syntax of the code after `await` with` async / await` is broken

![](https://pbs.twimg.com/media/DaRq5tLV4AEHKcJ.png)

**bug in image**

There are other bugs in which `if` images overlap.

![](https://pbs.twimg.com/media/DaR3v2OUQAA3yYy.png)

As a supplement, since it was generated from the extended function of vscode, it is a bug of vscode side.

Finally.
I am Japanese and English is not fluent, so please let me know if you do not understand the meaning.

Thanks.

**Comment by mfix22** [comment]
@konojunya your English is great! 😄  

As for styling of specific colors for specific languages is outside the scope of this project. A possible option would be to file an issue/PR to [CodeMirror](https://github.com/codemirror/CodeMirror), since they would have to make the updates for us to support this change. 

Will look into your other bug further.

**Comment by konojunya** [comment]
@mfix22 Thanks!

OK, I would like to open the issue to CodeMirror.

**Comment by mfix22** [comment]
Please do 😄
