### ISSUE TITLE
Carbon URLs

### ISSUE THREAD

**Issue by rauchg** [dawnlabs/carbon#429]
When the user first gets to carbon.now.sh, there exists a field that contains a URL that looks like this:

```
https://carbon.now.sh/$id
```

By default, it will be the URL matching the configuration settings and the content of the example carbon editor.

The url would be deterministic. You could generate it by producing a JSON object like this:

```json
{
  "fontSize": 12,
  "content": "int main(void){\nprintf('hello world');\nreturn 0;\n}"
}
```

… while ensuring the keys are sorted.

The user still would have to download the image independently for tweeting, but can also attach the URL for letting people read the code better, copy and paste and fork into their own carbon :D Come to think of it: carbon copy ? 🤯

**Comment by mfix22** [comment]
Hey Guillermo 👋 Glad to have you here!

We replicate [most](https://github.com/dawnlabs/carbon/blob/master/pages/index.js#L44-L46) of the Carbon state/settings to `window.location` so that you can just copy paste the browser's URL to share the current configuration. Does that work for your use case? Maybe I am mistaking something 🙂 

(Thanks again for Now and Next 🙏)

**Comment by mfix22** [comment]
I'm going to close this for now, @rauchg let me know if I didn't fully understand your feature idea 🙂
