### ISSUE TITLE
Fix `` highlighting for F#

### ISSUE THREAD

**Issue by Worldbeater** [dawnlabs/carbon#51]
There is an issue with how textual functions names are displayed for F#, please, take a look:

![carbon 1](https://user-images.githubusercontent.com/6759207/30927767-34a97d82-a3c2-11e7-8b85-4c4f33e240e7.png)

It would be great if words in function name could be colored using the same color.

**Comment by mfix22** [comment]
Hey @Worldbeater editing how the syntax looks for every language is out of the scope of this project, since we are just using the format found here: https://github.com/codemirror/CodeMirror/blob/master/mode/mllike/mllike.js

If you think the formatting is incorrect for F #, I would either file an issue with codemirror, or send a PR that fixes the formatting 😄
