### ISSUE TITLE
[Request theme] Lucy

### ISSUE THREAD

**Issue by mesqueeb** [dawnlabs/carbon#654]
I'd love this theme to be added!
LUCY
https://github.com/juliettepretot/lucy-vscode-theme

**Comment by mfix22** [comment]
@mesqueeb we also have custom themes now, so you can create this saved theme locally as well now too 👍

**Comment by mesqueeb** [comment]
@mfix22 If i create a new theme on the site by tapping "Create +" how will I know I will always be able to access it from any device?
I didn't see any user authentication to save the actual themes...

**Comment by mfix22** [comment]
It is saved to local storage, which can be deleted. I would save a copy offline just in case, since `localStorage` is obviously not a permanent solution.

That is interesting you mention wanting authentication though — we have been thinking about supporting GitHub auth to use to save your themes and snippets and such.

**Comment by mesqueeb** [comment]
@mfix22 great! If you use firebase auth service you can literally implement github auth in 5 minutes without sweat ; )
Be sure to check it out!!
