### ISSUE TITLE
Automatically deploy to website

### ISSUE THREAD

**Issue by andrewda** [dawnlabs/carbon#68]
Looks like the website is a bit behind the master branch. Automatic deploys could probably be done with [`now-travis`](https://github.com/eliperelman/now-travis) so that every push to master is deployed to https://carbon.now.sh/.

**Comment by briandennis** [comment]
Thanks for bringing this up! I think we're going to go with a release based scheme where we'll deploy when we feel sufficient progress has been made rather than after every commit. Additionally, we want to verify that the deployment is working properly before aliasing it, so I don't think we'll be automating this for the time being.

We definitely should set up some CI though to run linting!

**Comment by andrewda** [comment]
Sure, that sounds good!
