### ISSUE TITLE
Use `.github` for GitHub templates

### ISSUE THREAD

**Issue by yeskunall** [dawnlabs/carbon#92]
Maybe create a `.github/` folder at this point, and move `CONTRIBUTING.md` inside it? Also, maybe create an `ISSUE_TEMPLATE.md` and `PULL_REQUEST.md`?

But most importantly, in lieu of #79, I was thinking that maybe we can add a `CONTRIBUTORS.md` inside `.github/` and link it in `README.md` instead? This way the README itself doesn't have to get cluttered unnecessarily.

**Comment by jakedex** [comment]
Thanks for tackling this one, @yeskunall! I'm definitely on board with adding a `.github` folder, but I think we want to keep our contributors section in the `README.md` in order to keep it visible as possible. I'm all for moving it into a `CONTRIBUTORS.md` and linking down the road if it gets too cluttered. 

See https://github.com/kentcdodds/all-contributors#mandatory

**Comment by yeskunall** [comment]
Sure thing. This will make the build script a bit more tricky than it is right now, but I'll show you what I guys did in the PR.

Once that's approved, a PR for creating a `.github` folder will be up as well.

Cheers! ❤️

**Comment by yeskunall** [comment]
At work. No worries tho, this will definitely have a PR by today evening. Should we also introduce basic templates for issues and PRs?

**Comment by jakedex** [comment]
No rush! And yeah, let's add templates for both.
